apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /healthcheck
            pathType: Exact
            backend:
              service:
                name: "{{ .Chart.Name }}-service"
                port:
                  number: 8080
          - path: /fetch
            pathType: Exact
            backend:
              service:
                name: "{{ .Chart.Name }}-service"
                port:
                  number: 8080
          - path: /download_csv
            pathType: Exact
            backend:
              service:
                name: "{{ .Chart.Name }}-service"
                port:
                  number: 8080
