apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-deployment"
  namespace: {{ .Values.namespace }}
  labels:
    app: rickmorty
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: rickmorty
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rickmorty
    spec:
      containers:
        - image: "{{ .Values.deployment.image.name }}"
          name: "rickmorty"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
