name: Elementor Workflow

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yuvalpress/rickmorty:latest
        
  test-helm-chart:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0

      - name: Configure kubectl context
        run: |
          kubectl config get-contexts
          kubectl config set-context kind-chart-testing

      - name: Create the rickmorty namespace
        run: kubectl create ns rickmorty || true

      - name: Deploy the helm chart
        run: helm install rickmorty ./charts/rickmorty -f ./charts/rickmorty/values.yaml --wait --timeout 20s

      - name: Expose service to local address 127.0.0.1
        run: kubectl port-forward svc/yuvalpress-rickmorty-service 8080:8080 -n rickmorty

      - name: Test /healthcheck
        id: test_path
        uses: wei/curl@master
        with:
          args: "https://127.0.0.1:8080/healthcheck"

      - name: Test Output
        run: echo "API is live!"
        if: steps.test_path.outputs.*
