name: Elementor Workflow

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yuvalpress/rickmorty:latest
        
  create-cluster:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        
  deploy-helm-chart:
    runs-on: ubuntu-latest
    needs: create-cluster
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Lint Helm Charts
        uses: helm/chart-testing-action@v2.2.1
        with:
          command: lint
          config: ct.yaml

      - name: Install Helm Charts
        uses: helm/chart-testing-action@v2.2.1
        with:
          command: install
          config: ct.yaml
