name: Elementor Workflow

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: yuvalpress/rickmorty:latest
        
  create-cluster:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        
  deploy-helm-chart:
    runs-on: ubuntu-latest
    needs: create-cluster
    steps:
      - name: Deploy Helm Chart
        uses: azure/setup-helm@v1
      
      - name: Deploy Chart
        run: "helm upgrade --install rickmorty ./charts -f ./charts/values.yaml"
